#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: IvanLu
 * Date: 2019/4/7
 * Time: 2:03
 */
define('APP_PATH', __DIR__ . '/');
define('APP_DEBUG', true);
define("IN_TWIMI_PHP", "True", TRUE);
date_default_timezone_set('PRC');
require(APP_PATH . 'BunnyPHP/BunnyPHP.php');
(new BunnyPHP(BunnyPHP::MODE_CLI))->run();